Dev/delete timestamps
SW-10/smartsendercpp pull request #18
Opened 2023-03-15 14:56 UTC by karljohan12

Good luck

2023-03-15 18:41 UTC, teisvh commented on src/managers/ModelManager.cpp
> +        //TODO Check on empty vector, but bug now
bug now??

2023-03-15 18:43 UTC, teisvh commented on src/managers/ModelManager.cpp
> +        if (container.cachedValues.startTimestamp == 0){
Er det fordi, den bliver initialiseret til 0, at dette tjek laves? I så fald, kan det ikke føre til fejl, idet '0' er en valid start timestamp?

2023-03-15 18:47 UTC, teisvh commented on src/managers/ModelManager.cpp
> +            largestUsedTimestamp = std::min(container.cachedValues.startTimestamp, largestUsedTimestamp);
hvorfor ikke bare sætte largestUsedTimestamp = container.cachedValues.startTimestamp?

2023-03-15 18:51 UTC, teisvh commented on src/managers/ReaderManager.cpp
> +            if (lastTimestampFlush + timestampFlusherPenalty == lineNumber){
ikke forkert, men gerne lige en parantes rundt om regnestykket

2023-03-15 18:54 UTC, teisvh commented on src/managers/TimestampManager.cpp
> +        for (auto &lol : localOffsetList){
underlig indentation her?

2023-03-15 19:03 UTC, teisvh commented on src/managers/TimestampManager.cpp
> +                latestTimestamps[lol.first].timestampFirst - index;
den her expression bliver ikke assignet til noget?

2023-03-15 19:05 UTC, teisvh commented on src/managers/TimestampManager.cpp
der må meget gerne blive sat nogle kommentarer i det her kode

2023-03-15 21:33 UTC, karljohan12 commented on src/managers/ModelManager.cpp
> +        //TODO Check on empty vector, but bug now
Okay dårligt fomuleret, .empty er bug lige nu.

2023-03-15 21:34 UTC, karljohan12 commented on src/managers/ModelManager.cpp
> +        //TODO Check on empty vector, but bug now
Så derfor har jeg ændret

2023-03-15 21:38 UTC, karljohan12 commented on src/managers/ModelManager.cpp
> +        if (container.cachedValues.startTimestamp == 0){
Jo, man kunne måske sætte til -1

2023-03-15 21:42 UTC, karljohan12 commented on src/managers/ModelManager.cpp
> +            largestUsedTimestamp = std::min(container.cachedValues.startTimestamp, largestUsedTimestamp);
Så vil du aldrig fange den mindste værdi. Er det ikke samme som bare tage det sidste index så?

Eller mener du 147 hvor container er uden for scope. Fordi samtdig ved man ikke om der eksisterer nogle cached values

2023-03-15 21:44 UTC, karljohan12 commented on src/managers/ReaderManager.cpp
> +            if (lastTimestampFlush + timestampFlusherPenalty == lineNumber){
Fixed

2023-03-15 21:48 UTC, karljohan12 commented on src/managers/TimestampManager.cpp
> +                latestTimestamps[lol.first].timestampFirst - index;
spædende🙈

2023-03-15 21:52 UTC, karljohan12 commented on src/managers/TimestampManager.cpp
> +                latestTimestamps[lol.first].timestampFirst - index;
fixd

2023-03-15 22:08 UTC, karljohan12 commented on src/managers/TimestampManager.cpp
done

2023-03-15 23:09 UTC, teisvh commented on src/managers/ModelManager.cpp
> +            largestUsedTimestamp = std::min(container.cachedValues.startTimestamp, largestUsedTimestamp);
nåh ja, kan godt se det nu

2023-03-16 08:46 UTC, agneborn98 requested changes

2023-03-16 08:46 UTC, agneborn98 commented on src/managers/TimestampManager.cpp
> +TEST_CASE("CHECK localoffset is remove"){
removed

2023-03-16 08:46 UTC, agneborn98 commented on src/managers/TimestampManager.cpp
> +        // How many timestamps which has not been flushed in current instance
that have not been

2023-03-16 08:47 UTC, karljohan12 commented on src/managers/TimestampManager.cpp
> +TEST_CASE("CHECK localoffset is remove"){
fixet

2023-03-16 08:47 UTC, karljohan12 commented on src/managers/TimestampManager.cpp
> +        // How many timestamps which has not been flushed in current instance
fixed

2023-03-16 08:48 UTC, agneborn98 approved these changes

2023-03-16 09:02 UTC, teisvh approved these changes

2023-03-16 09:05 UTC, merged