Vectorbased
SW-10/smartsendercpp pull request #8
Opened 2023-02-21 14:39 UTC by teisvh

2023-02-21 14:59 UTC, karljohan12 requested changes

2023-02-21 14:59 UTC, karljohan12 commented on src/models/vector_based.cpp
> +int VectorBased::fitValue(long time_stamp, double latitude, double longitude, float error){
Camelcase timestamp

2023-02-21 14:59 UTC, karljohan12 commented on src/models/vector_based.cpp
> +#define TO_RAD (3.1415926536 / 180)
camelcase

2023-02-21 14:59 UTC, karljohan12 commented on src/models/vector_based.cpp
> +        errorSum += (float)m_distance;
camelcase

2023-02-21 14:59 UTC, karljohan12 commented on src/models/vector_based.h
> +    int current_delta;
Camelcase

2023-02-21 14:59 UTC, karljohan12 commented on src/models/vector_based.cpp
> +        prediction.longitude = current.longitude + (vec.x * (double)(current_delta));
Er det nødvendigt at cast current_delta til double?

2023-02-21 14:59 UTC, karljohan12 commented on src/models/vector_based.cpp
> +        vec.x = vec.x / (double)(current_delta);
Nødvendigt at cast til double?

2023-02-21 15:05 UTC, teisvh commented on src/models/vector_based.cpp
> +        prediction.longitude = current.longitude + (vec.x * (double)(current_delta));
ser ikke sådan ud

2023-02-21 15:07 UTC, teisvh commented on src/models/vector_based.cpp
> +        vec.x = vec.x / (double)(current_delta);
nope

2023-02-21 15:10 UTC, teisvh commented on src/models/vector_based.cpp
> +        errorSum += (float)m_distance;
fixed

2023-02-21 15:12 UTC, teisvh commented on src/models/vector_based.h
> +    int current_delta;
fixed

2023-02-21 15:13 UTC, teisvh commented on src/models/vector_based.cpp
> +        prediction.longitude = current.longitude + (vec.x * (double)(current_delta));
fixed

2023-02-21 15:13 UTC, teisvh commented on src/models/vector_based.cpp
> +        vec.x = vec.x / (double)(current_delta);
fixed

2023-02-21 15:13 UTC, teisvh commented on src/models/vector_based.cpp
> +int VectorBased::fitValue(long time_stamp, double latitude, double longitude, float error){
fixed

2023-02-21 15:53 UTC, karljohan12 approved these changes

2023-02-22 17:00 UTC, agneborn98 approved these changes
Ser ud til at Emil fangede alt, approved!

2023-02-22 17:01 UTC, merged